CREATE OR REPLACE FORCE VIEW "KBD2A08"."OPER_BANK_VIEW" (
    "NAZWA_NADAWCY", 
    "NR_KONTA_NADAWCY", 
    "NR_KONTA_ODBIORCY", 
    "KWOTA", 
    "TYTUL", 
    "DATA_OPERACJI"
) AS 
SELECT 
    knd.NAZWA AS NAZWA_NADAWCY, 
    knd.NR_KONTA AS NR_KONTA_NADAWCY, 
    ko.NR_KONTA AS NR_KONTA_ODBIORCY, 
    o.KWOTA, 
    o.TYTUL, 
    o.DATA_OPERACJI 
FROM OPERACJE_BANKOWE o
JOIN KONTA ko ON ko.ID_KONTA = o.ID_KONTA_ODBIORCY
JOIN (
    SELECT k.ID_KONTA, d.NAZWA, k.NR_KONTA
    FROM KONTA k
    JOIN DARCZYNCY d ON k.ID_DARCZYNCY = d.ID_DARCZYNCY
    ) knd
ON knd.ID_KONTA = o.ID_KONTA_NADAWCY;
/

COMMENT ON TABLE OPER_BANK_VIEW IS 'Perspektywa sluzaca do wyswietlania oraz wprowadzania operacji bankowych. Dane pochodza z trzech tabel: OPERACJE_BANKOWE, KONTA oraz DARCZYNCY. W przypadku wprowadzania danych, wyzwalacz OPER_BANK_VIEW_INSERT_TRG zapewnia jednoznaczne rozdystrybuowanie danych do tabel zrodlowych (zob. komentarz w kodzie wyzwalacza).';


CREATE OR REPLACE VIEW DAROWIZNY_DLA_PODOP_VIEW (
    ID_OPERACJI,
    "DATA OPERACJI",
    TYTUL,
    KWOTA,
    PODOPIECZNY
) AS
SELECT O.ID_OPERACJI, O.DATA_OPERACJI, O.TYTUL, O.KWOTA, NVL2(O.ID_PODOP, P.IMIE||' '||P.NAZWISKO, 'brak przypisania')
FROM OPERACJE_BANKOWE O
LEFT JOIN PODOPIECZNI P ON O.ID_PODOP = P.ID_PODOP;
/

COMMENT ON TABLE DAROWIZNY_DLA_PODOP_VIEW IS 'Lista operacji z imieniem i nazwiskiem podopiecznego. Jesli operacja nie jest przypisana do zadnego podopiecznego to zamiast nazwiska zwracane jest ''brak przypisania''.';


DROP MATERIALIZED VIEW LOG ON OPERACJE_BANKOWE;
DROP MATERIALIZED VIEW SUMY_DAROWIZN_MVIEW;

CREATE MATERIALIZED VIEW SUMY_DAROWIZN_MVIEW
BUILD IMMEDIATE
REFRESH FORCE
-- ON [COMMIT | DEMAND ]
ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT P.ID_PODOP, P.IMIE,P.NAZWISKO, P.EMAIL, EXTRACT(YEAR FROM O.DATA_OPERACJI) AS ROK, EXTRACT(MONTH FROM O.DATA_OPERACJI) AS MIESIAC, SUM(KWOTA) AS SUMA_DAROWIZN
FROM OPERACJE_BANKOWE O
JOIN PODOPIECZNI P ON O.ID_PODOP = P.ID_PODOP
GROUP BY P.ID_PODOP, P.EMAIL, P.IMIE, P.NAZWISKO, EXTRACT(YEAR FROM O.DATA_OPERACJI), EXTRACT(MONTH FROM O.DATA_OPERACJI);
/

COMMENT ON TABLE SUMY_DAROWIZN_MVIEW IS 'Perspektywa zmaterializowana wyswietlajaca sume wplaconych darowizn dla kazdego podopiecznego, z podzialem na lata i miesiace. Wymaga recznego odswiezenia.';


CREATE MATERIALIZED VIEW LOG ON OPERACJE_BANKOWE 
WITH PRIMARY KEY 
INCLUDING NEW VALUES;
/

DROP MATERIALIZED VIEW WPLATY_DARCZYNCOW_MVIEW;

CREATE MATERIALIZED VIEW WPLATY_DARCZYNCOW_MVIEW
BUILD IMMEDIATE
REFRESH FORCE
ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT D.ID_DARCZYNCY, D.NAZWA, D.EMAIL, SUM(KWOTA) AS SUMA_DAROWIZN FROM DARCZYNCY D
JOIN KONTA K ON K.ID_DARCZYNCY = d.id_darczyncy
JOIN OPERACJE_BANKOWE O ON O.ID_KONTA_NADAWCY = K.ID_KONTA
GROUP BY D.ID_DARCZYNCY, D.NAZWA, D.EMAIL;
/

COMMENT ON TABLE WPLATY_DARCZYNCOW_MVIEW IS 'Perspektywa zmaterializowana wyswietlajaca sumy darowizn wplaconych przez poszczegolnych darczyncow.';