CREATE OR REPLACE FORCE VIEW "KBD2A08"."OPER_BANK_VIEW" (
    "NAZWA_NADAWCY", 
    "NR_KONTA_NADAWCY", 
    "NR_KONTA_ODBIORCY", 
    "KWOTA", 
    "TYTUL", 
    "DATA_OPERACJI"
) AS 
SELECT 
    knd.NAZWA AS NAZWA_NADAWCY, 
    knd.NR_KONTA AS NR_KONTA_NADAWCY, 
    ko.NR_KONTA AS NR_KONTA_ODBIORCY, 
    o.KWOTA, 
    o.TYTUL, 
    o.DATA_OPERACJI 
FROM OPERACJE_BANKOWE o
JOIN KONTA ko ON ko.ID_KONTA = o.ID_KONTA_ODBIORCY
JOIN (
    SELECT k.ID_KONTA, d.NAZWA, k.NR_KONTA
    FROM KONTA k
    JOIN DARCZYNCY d ON k.ID_DARCZYNCY = d.ID_DARCZYNCY
    ) knd
ON knd.ID_KONTA = o.ID_KONTA_NADAWCY;
/