SET SQLBLANKLINES ON
CREATE TABLE PODOPIECZNI 
(
  ID_PODOP NUMBER(4) GENERATED ALWAYS AS IDENTITY NOT NULL 
, IMIE VARCHAR2(20) NOT NULL 
, NAZWISKO VARCHAR2(40) NOT NULL 
, STATUS CHAR(1) DEFAULT 'A' NOT NULL 
, EMAIL VARCHAR2(254) 
, UWAGI VARCHAR2(1000) 
, CONSTRAINT PODOPIECZNI_PK PRIMARY KEY 
  (
    ID_PODOP 
  )
  ENABLE 
);

ALTER TABLE PODOPIECZNI
ADD CONSTRAINT PODOP_EMAIL_UN UNIQUE 
(
  EMAIL 
)
ENABLE;

ALTER TABLE PODOPIECZNI
ADD CONSTRAINT PODOP_STAT_CK CHECK 
(STATUS IN ('A', 'N'))
ENABLE;

COMMENT ON COLUMN PODOPIECZNI.IMIE IS 'Maksymalnie 20 znakow.';

COMMENT ON COLUMN PODOPIECZNI.NAZWISKO IS 'Maksymalnie 40 znakow.';

COMMENT ON COLUMN PODOPIECZNI.STATUS IS 'Wartosc ''A'' (aktywny) lub ''N'' (nieaktywny).';

COMMENT ON COLUMN PODOPIECZNI.UWAGI IS 'Opcjonalne, dodatkowe informacje.';

CREATE SEQUENCE PODOP_SEQ;
