CREATE OR REPLACE TRIGGER ID_OPER_SEQ_TRG 
BEFORE INSERT ON OPERACJE_BANKOWE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_OPERACJI IS NULL THEN
      SELECT ID_OPER_SEQ.NEXTVAL INTO :NEW.ID_OPERACJI FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
