CREATE OR REPLACE TRIGGER ID_OPER_BANK_SEQ_TRG
BEFORE INSERT ON OPERACJE_BANKOWE
FOR EACH ROW WHEN (NEW.ID_OPERACJI IS NULL)
BEGIN
SELECT ID_OPER_BANK_SEQ.NEXTVAL INTO :NEW.ID_OPERACJI FROM dual;
END;
/
