CREATE OR REPLACE TRIGGER ID_SLOWA_KL_SEQ_TRG 
BEFORE INSERT ON SLOWA_KLUCZOWE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_SLOWA_KL IS NULL THEN
      SELECT ID_SLOWA_KL_SEQ.NEXTVAL INTO :NEW.ID_SLOWA_KL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


CREATE OR REPLACE TRIGGER ID_SLOWA_KL_SEQ_TRG
BEFORE INSERT ON SLOWA_KLUCZOWE
FOR EACH ROW WHEN (NEW.ID_SLOWA_KL IS NULL)
BEGIN
SELECT ID_SLOWA_KL_SEQ.NEXTVAL INTO :NEW.ID_SLOWA_KL FROM dual;
END;
/
